name: Playwright Tests inside Docker

on:
  push:
    branches: [ main, master, playwright_githubactions ]
  pull_request:
    branches: [ main, master ]

jobs:
  playwright-run:
    runs-on: ubuntu-latest
    
    container:
      image: mcr.microsoft.com/playwright:v1.39.0-jammy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: xvfb-run npx playwright test --project=chromium
        env:
          BASE_URL: https://qauto.forstudy.space
          HTTP_USERNAME: ${{ secrets.HTTP_USERNAME }}
          HTTP_PASSWORD: ${{ secrets.HTTP_PASSWORD }}